---
title: "Correlation Function"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{package_intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Correlation Overview

TangledFeatures attempts to automatically identify the optimal correlation between the two variables based upon the variable type. by default there will be some set correlations that can be viewed and changed. All correlations in the process can also be viewed using the (View). Command

Correlation output can be viewed as a DAG through the ggplot package and can be visualized. 

if the auto correlation method is set , we are able to return the various pairs of variables as well as the correlation metric that was used between them. 

You can also manually set the correlation type in the function itself.

## Installation

You can install the development version of TangledFeatures from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("Allen-1242/TangledFeatures")
```

## Example

This is a basic example which shows you how to solve a common problem:

``` r
library(TangledFeatures)
Taking the correlation as cor_total_df)
```

